site_name: Metacentrum Documentation
docs_dir: docs
site_url: https://docs.metacentrum.cz

extra:
  generator: false
  version: !ENV [SITE_VERSION, 'undef_build_number']
  site_title: e-INFRA CZ Documentation

theme:
  name: material
  language: 'en'    
  features:
    - navigation.tabs
#    - navigation.sections
  font:
    text: 'Ubuntu'
    code: 'Source Code Pro'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 'Overview': index.md
  - Access: access/index.md
  - Basics:
    - basics/index.md
  - 'Advanced':
    - advanced/index.md
    - advanced/pbs-options/index.md
    - advanced/queues-in-meta/index.md
  - Applications:
    - applications/index.md
  - 'Troubleshooting':
    - troubleshooting/faqs/index.md
    - troubleshooting/outages/index.md
    - troubleshooting/known-issues/index.md
  - Contact:
    - contact/index.md
  - Tutorials:
    - tutorials/index.md
