site_name: Metacentrum Documentation
docs_dir: docs
site_url: https://docs.metacentrum.cz

extra:
  generator: false
  version: !ENV [SITE_VERSION, 'undef_build_number']
  site_title: e-INFRA CZ Documentation

theme:
  name: material
  language: 'en'
  features:
    - navigation.tabs
  font:
    text: 'Ubuntu'
    code: 'Source Code Pro'

nav:
  - 'Overview': index.md
  - Access: access/index.md
#  - Access: 
#      - Get account: access/get-account/get-account-meta.md
  - Basics:
    - basics/index.md
  - Advanced:
    - advanced/index.md
  - Applications:
    - applications/index.md
  - Troubleshooting:
    - troubleshooting/index.md
