site_name: Metacentrum Documentation
docs_dir: docs
site_url: https://docs.metacentrum.cz

extra:
  generator: false
  version: !ENV [SITE_VERSION, 'undef_build_number']
  site_title: e-INFRA CZ Documentation

# custom stylesheet
extra_css:
  - stylesheets/metacentrum_custom.css

theme:
  name: material
  language: 'en'    
  features:
    - navigation.tabs
#    - navigation.sections
  font:
    text: 'Ubuntu'
    code: 'Source Code Pro'

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.snippets:
      base_path: 'docs/snippets'
  - codehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - 'Access':
    - access/terms/index.md
    - access/account/index.md
    - access/log-in/index.md
    - access/perun/index.md
    - access/pbsmon/index.md
  - 'Basics':
    - basics/concepts/index.md
    - basics/jobs/index.md
  - 'Data':
    - data/data-within/index.md
    - data/data-outside/index.md
    - data/backup-archive/index.md
    - data/quotas/index.md
  - 'Software':
    - 'Graphical software':
      - software/graphical/ondemand/index.md
      - software/graphical/galaxy.md
      - software/graphical/kube-rancher.md
      - software/graphical/jupyter-ntb.md
      - software/graphical/rstudio.md
      - software/graphical/ansys.md
      - software/graphical/matlab.md
      - software/graphical/vmd.md
      - software/graphical/alphafold.md
    - software/modules/index.md
    - software/install-software/index.md
    - 'Frequently used software':
      - 'Chemistry':
        - software/available-soft/sw-list/amber.md
        - software/available-soft/sw-list/gaussian.md
        - software/available-soft/sw-list/molden.md
        - software/available-soft/sw-list/molpro.md
        - software/available-soft/sw-list/turbomole.md
        - software/available-soft/sw-list/vasp.md
        - software/available-soft/sw-list/wien2k.md
      - 'Genomics':
        - software/available-soft/sw-list/clcbio-genomics-wb.md
        - software/available-soft/sw-list/geneious.md
      - 'Compilers, debuggers':
        - software/available-soft/sw-list/allinea-ddt.md
        - software/available-soft/sw-list/intel.md
        - software/available-soft/sw-list/pgi-cdk.md
        - software/available-soft/sw-list/total-view.md
      - 'Mechanics':
        - software/available-soft/sw-list/ansys.md
      - 'Mathematics':
        - software/available-soft/sw-list/maple.md
        - software/available-soft/sw-list/matlab.md
        - software/available-soft/sw-list/wolfram-math.md   
#      - 'Singularity images':
#        - software/available-soft/sw-list/singularity.md
    - software/full-list/index.md
  - 'Advanced':
    - 'Access and security':
      - advanced/connect-auth/index.md
      - advanced/kerberos/index.md
    - 'PBS and job planning':    
      - advanced/pbs-options/index.md
      - advanced/queues-in-meta/index.md
    - 'Job state and history':
      - advanced/job-tracking/index.md
    - 'Ingrastructure':  
      - advanced/grid-infrastruct/index.md
      - advanced/mount-storages/index.md
    - advanced/gpu-comput/index.md
    - advanced/parallel-comput/index.md
    - advanced/containers/index.md
    - advanced/run-graphical/index.md
  - 'Troubleshooting':
    - troubleshooting/faqs/index.md
    - troubleshooting/outages/index.md
    - troubleshooting/known-issues/index.md
  - 'User support':
    - contact/index.md
    - contact/write-request/index.md
  - Tutorials:
    - tutorials/index.md
