site_name: Metacentrum Documentation
docs_dir: docs
site_url: https://docs.metacentrum.cz

extra:
  generator: false
  version: !ENV [SITE_VERSION, 'undef_build_number']
  site_title: e-INFRA CZ Documentation

theme:
  name: material
  language: 'en'    
  features:
    - navigation.tabs
#    - navigation.sections
  font:
    text: 'Ubuntu'
    code: 'Source Code Pro'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.snippets:
      base_path: 'docs/snippets'
  - codehilite
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - 'Access':
    - access/terms/index.md
    - access/account/index.md
    - access/log-in/index.md
    - access/perun/index.md
    - access/pbsmon/index.md
  - Basics:
    - basics/index.md
  - 'Advanced':
    - advanced/connect-auth/index.md
    - advanced/pbs-options/index.md
    - advanced/queues-in-meta/index.md
    - advanced/job-tracking/index.md
    - advanced/grid-infrastruct/index.md
    - advanced/work-data/index.md
    - advanced/mount-storages/index.md
    - advanced/kerberos/index.md
    - advanced/run-graphical/index.md
    - advanced/ondemand/index.md
    - advanced/gpu-comput/index.md
    - advanced/containers/index.md
    #- advanced/modules/index.md
    #- advanced/install-software/index.md
    #- advanced/parallel-comput/index.md
  - Applications:
    - applications/index.md
  - 'Troubleshooting':
    - troubleshooting/faqs/index.md
    - troubleshooting/outages/index.md
    - troubleshooting/known-issues/index.md
  - Contact:
    - contact/index.md
  - Tutorials:
    - tutorials/index.md
  - TODO:
    - TODO/index.md
