site_name: Metacentrum Documentation
docs_dir: docs
site_url: https://docs.metacentrum.cz

extra:
  generator: false
  version: !ENV [SITE_VERSION, 'undef_build_number']
  site_title: e-INFRA CZ Documentation

theme:
  name: material
  language: 'en'    
  features:
    - navigation.tabs
#    - navigation.sections
  font:
    text: 'Ubuntu'
    code: 'Source Code Pro'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.snippets:
      base_path: 'docs/snippets'
  - codehilite
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - 'Access':
    - access/terms/index.md
    - access/account/index.md
    - access/log-in/index.md
    - access/perun/index.md
    - access/pbsmon/index.md
  - 'Basics':
    - basics/concepts/index.md
    - basics/jobs/index.md
  - 'Advanced':
    - 'Access and security':
      - advanced/connect-auth/index.md
      - advanced/kerberos/index.md
    - 'PBS and job planning':    
      - advanced/pbs-options/index.md
      - advanced/queues-in-meta/index.md
    - 'Job state and history':
      - advanced/job-tracking/index.md
    - 'Data and grid':  
      - advanced/grid-infrastruct/index.md
      - advanced/work-data/index.md
      - advanced/mount-storages/index.md
    - 'Specific types of jobs':
      - advanced/gpu-comput/index.md
      - advanced/containers/index.md
      - advanced/parallel-comput/index.md
    - 'Non-CLI access':
      - advanced/run-graphical/index.md
      - advanced/ondemand/index.md
  - 'Software':
    - software/modules/index.md
    - software/install-software/index.md
    - 'Frequently used software':
      - software/available-soft/sw-list/allinea-ddt.md
      - software/available-soft/sw-list/amber.md
      - software/available-soft/sw-list/ansys.md
      - software/available-soft/sw-list/clcbio-genomics-wb.md
      - software/available-soft/sw-list/gaussian.md
      - software/available-soft/sw-list/geneious.md
      - software/available-soft/sw-list/intel.md
      - software/available-soft/sw-list/maple.md
      - software/available-soft/sw-list/matlab.md
      - software/available-soft/sw-list/molpro.md
      - software/available-soft/sw-list/pgi-cdk.md
      - software/available-soft/sw-list/total-view.md
      - software/available-soft/sw-list/turbomole.md
      - software/available-soft/sw-list/wien2k.md
      - software/available-soft/sw-list/wolfram-math.md
      - 'Chemistry':
        - software/available-soft/sw-list/respect.md
      - 'Physics':
        - software/available-soft/sw-list/vasp.md
      - 'Compilers':
        - software/available-soft/sw-list/molden.md
      - 'Programming languages':
        - software/available-soft/sw-list/r.md
      - 'Data science':
        - software/available-soft/sw-list/ds.md
      - 'Machine learning':
        - software/available-soft/sw-list/ml.md
      - 'Singularity images':
        - software/available-soft/sw-list/singularity.md
    - software/full-list/index.md
  - 'Troubleshooting':
    - troubleshooting/faqs/index.md
    - troubleshooting/outages/index.md
    - troubleshooting/known-issues/index.md
  - 'User support':
    - contact/index.md
    - contact/write-request/index.md
  - Tutorials:
    - tutorials/index.md
